# Programa que pide al usuario un numero entre el 1 y el 10 y devuelve ese mismo numero en romano
import os;os.system('cls')
print('Conversión de números arabigos a romanos')
n=int(input('Ingresa un número entero entre el 1 y el 10: '))
if n==1:print(f'\n{n} = I')
elif n==2:print(f'\n{n} = II')
elif n==3:print(f'\n{n} = III')
elif n==4:print(f'\n{n} = IV')
elif n==5:print(f'\n{n} = V')
elif n==6:print(f'\n{n} = VI')
elif n==7:print(f'\n{n} = VII')
elif n==8:print(f'\n{n} = VIII')
elif n==9:print(f'\n{n} = IX')
elif n==10:print(f'\n{n} = X')
else: print('\nError: número fuera de rango')
print('\nFin')